import Head from "next/head";
import { Login } from "../components/Login";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();
  if (!isAuthenticated) return <Login />;

  return (
    <div>
      <Head>
        <title>anonimous chatt app </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>wellcome to the App </h1>
      <button onClick={logout}>logout</button>
    </div>
  );
}
